### PR TITLE
Revises the licensing section

### LINKED ISSUE #8: software licenses
I'm adding stub information, and someone with more expertise should flesh out that information.  Just be sure to keep an unbiased voice. These selections are meant to be by the authors and we should respect their desires, even if we (of the open source communities) might disagree with them.

### PR DESCRIPTION
**Pull request by hlapp**
Closes #8.

### CODE REVIEW

**Comment by hlapp** [comment]
I need to get this ready for teaching tomorrow. Any comments from anyone (esp. @dsoto, @elliewix, @raynamharris, @ErinBecker) before I merge this?

**Comment by elliewix** [comment]
* might want to define/link out to what ePHI is, and potentially include more examples, e.g. protected human subject data, proprietary data from another party, health information such as PHI or HIPAA information, or data that could threaten national security
* expand/link out to what DUA is

**Comment by hlapp** [comment]
Thanks @elliewix. I think I addressed both of your comments. As for DUAs, I really don't think this is a good place to promote these, but I added information as to why, and some examples people might encounter to the instructor notes.

**Comment by elliewix** [comment]
http://www.openstreetmap.org/copyright might be another interesting use case to highlight

**Comment by hlapp** [comment]
Indeed. Added to the instructor notes.

**Pull request merged**
