### PR TITLE
Adds more content about ORCIDs

### LINKED ISSUE #5: Need more/informed ORCiD information
I'm placing in stub information but it should be reviewed by a more informed ORCiD person.  Perhaps reach out to the orcid outreach team to provide materials?

### LINKED ISSUE #9: ORCiDs
Finish orcid section of publishing lesson

### PR DESCRIPTION
**Pull request by hlapp**
Closes #5 and also closes #9.

### CODE REVIEW

**Comment by hlapp** [comment]
Getting this ready for teaching tomorrow. Any comments from anyone (esp. @dsoto, @elliewix, @raynamharris, @ErinBecker) before I merge this?

**Comment by ErinBecker** [comment]
Looks good to me!

**Comment by raynamharris** [comment]
Looks good! Just suggested a minor change to give all the exercises a level three header

**Comment by dsoto** [comment]
The new motivation for using ORCID ids is very helpful.

**Pull request merged**
